events {}

http {
    upstream itemsrv {
        server item-service:8081;
    }
    upstream ordersrv {
        server order-service:8082;
    }
    upstream paymentsrv {
        server payment-service:8083;
    }

    server {
        listen 8080;

        location /items {
            proxy_pass http://itemsrv;
        }
        location /orders {
            proxy_pass http://ordersrv;
        }
        location /payments {
            proxy_pass http://paymentsrv;
        }
    }
}
