events {}

http {
    upstream item_service {
        server item-service:8081;
    }
    upstream order_service {
        server order-service:8082;
    }
    upstream payment_service {
        server payment-service:8083;
    }

    server {
        listen 8080;

        location /items/ {
            proxy_pass http://item_service;
        }
        location /orders/ {
            proxy_pass http://order_service;
        }
        location /payments/ {
            proxy_pass http://payment_service;
        }
    }
}
